- build: examples/1-simple
  photon: [0.6.3, 0.7.0, 0.8.0-rc.12, 1.0.0]
  p1: [latest]
  electron: [0.6.4, 0.7.0, 0.8.0-rc.12, 1.0.0]
  argon: [0.8.0-rc.27]
  boron: [0.8.0-rc.27]
  xenon: [0.8.0-rc.27]
- build: examples/2-selftest-SC16IS740RK
  photon: [latest]
- build: examples/3-simple-spi-SC16IS740RK
  photon: [1.0.0]
  argon: [0.8.0-rc.27]
